apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: migration-demo
resources:
  - namespace.yaml
  - configuration.yaml
  - rbac.yaml
  - storage.yaml
  - database.yaml
  - api.yaml
  - frontend.yaml
  - worker.yaml
  - operations.yaml
  - policies.yaml
