apiVersion: v1
kind: Namespace
metadata:
  name: migration-demo
  labels:
    app.kubernetes.io/part-of: navigan-migration-reference
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
