apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: navigan-platform
  namespace: argocd
spec:
  description: Mandatory Navigan-managed cluster utilities
  sourceRepos:
    - __SYSTEM_REPO_URL__
    - https://prometheus-community.github.io/helm-charts
    - https://falcosecurity.github.io/charts
    - https://kubernetes-sigs.github.io/headlamp
  destinations:
    - server: https://kubernetes.default.svc
      namespace: argocd
    - server: https://kubernetes.default.svc
      namespace: kube-system
    - server: https://kubernetes.default.svc
      namespace: navigan-system
    - server: https://kubernetes.default.svc
      namespace: navigan-monitoring
    - server: https://kubernetes.default.svc
      namespace: navigan-security
    - server: https://kubernetes.default.svc
      namespace: navigan-dashboard
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  orphanedResources:
    warn: true
