apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/name: navigan-migration-connector
    app.kubernetes.io/managed-by: Helm
automountServiceAccountToken: false
